version: "3.2"
services:
  my_db:
    build: ./database/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
  app:
    build: ./app/
    command: >
          python3 app.py  
    volumes:
      - .:/code
    ports:
      - 12390:12390
    depends_on:
      - my_db   
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - my_db      
      - app         
volumes:
  grafana-data:
    external: true
